export const ADMIN_REQUEST ='[ADMIN_REQUEST]'
export const ADMIN_SUCCESS ='[ADMIN_SUCCESS]'
export const ADMIN_FAIL ='[ADMIN_FAIL]'

export const CREATE_ADMIN ='[CREATE_ADMIN]'
export const CREATE_PET ='[CREATE_PET]'
export const CHECK_ADMIN ='[CHECK_ADMIN]'
export const CREATEPET_DETS ='[CREATEPET_DETS]'
export const UPDATE_PET ='[UPDATE_PET]'
export const REMOVE_ADMIN ='[REMOVE_ADMIN]'
export const DELETEPET ='[DELETEPET]'
